In [1]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.sum(arr)) 
print(np.sum(arr, axis=0)) 
print(np.sum(arr, axis=1)) 


10
[4 6]
[3 7]


In [15]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.mean(arr)) 
print(np.mean(arr, axis=0)) 
print(np.mean(arr, axis=1))

2.5
[2. 3.]
[1.5 3.5]


In [3]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.max(arr)) 
print(np.max(arr, axis=0)) 
print(np.max(arr, axis=1)) 

4
[3 4]
[2 4]


In [4]:
print(np.min(arr))
print(np.min(arr, axis=0))
print(np.min(arr, axis=1)) 

1
[1 2]
[1 3]


In [5]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.median(arr)) 
print(np.median(arr, axis=0))
print(np.median(arr, axis=1)) 

2.5
[2. 3.]
[1.5 3.5]


In [6]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.prod(arr)) 
print(np.prod(arr, axis=0))
print(np.prod(arr, axis=1))


24
[3 8]
[ 2 12]


In [7]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.std(arr))
print(np.std(arr, axis=0)) 
print(np.std(arr, axis=1)) 

1.118033988749895
[1. 1.]
[0.5 0.5]


In [8]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.var(arr)) 
print(np.var(arr, axis=0))
print(np.var(arr, axis=1)) 


1.25
[1. 1.]
[0.25 0.25]


In [9]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result) 

[5 7 9]


In [10]:
import numpy as np
arr1 = np.array([4, 5, 6])
arr2 = np.array([1, 2, 3])
result = arr1 - arr2
print(result) 

[3 3 3]


In [11]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 * arr2
print(result) 

[ 4 10 18]


In [12]:
import numpy as np
arr1 = np.array([4, 6, 8])
arr2 = np.array([2, 3, 4])
result = arr1 / arr2
print(result) 


[2. 2. 2.]


In [13]:
import numpy as np
arr = np.array([2, 3, 4])
result = arr ** 2
print(result)

[ 4  9 16]


In [14]:
import numpy as np
arr = np.array([4, 9, 16])
result = np.sqrt(arr)
print(result)


[2. 3. 4.]


In [16]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 2, 3])
result = arr1 == arr2
print(result) 


[False  True  True]


In [17]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
result_mean = np.mean(arr)
result_std = np.std(arr, axis=1)
result_sum = np.sum(arr, axis=0)
print(result_mean)
print(result_std) 
print(result_sum)

3.5
[0.81649658 0.81649658]
[5 7 9]


In [18]:
import numpy as np
arr = np.array([2.3, 4.7, 6.1])
result = np.round(arr)
print(result)

[2. 5. 6.]


In [19]:
import numpy as np
arr = np.array([2, 3, 4])
result = np.power(arr, 2)
print(result) 

[ 4  9 16]


In [20]:
import numpy as np
arr = np.array([1, 5, 10])
result = np.where(arr < 5, arr, 0)
print(result)

[1 0 0]


In [22]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
result = np.cumsum(arr)
print(result)


[ 1  3  6 10 15]


In [23]:
import numpy as np
arr = np.array([3, 1, 4, 2, 5])
result = np.sort(arr)
print(result) 

[1 2 3 4 5]


In [24]:
S_X = np.array([[2, 5, 6, 5],[4, 8, 6, 5]])
S_Y = np.array([[6, 7, 5, 9],[7, 5, 6, 4]])
quarterly_difference = S_Y - S_X
print(quarterly_difference)

[[ 4  2 -1  4]
 [ 3 -3  0 -1]]


In [25]:
less_than_2 = S_X < 2
print(less_than_2)

[[False False False False]
 [False False False False]]


In [29]:
X_cumsum = np.cumsum(S_X, axis = 1)
print(X_cumsum)


print( X_cumsum >= 8)

Y_cumsum = np.cumsum(S_Y, axis = 1)
print(Y_cumsum)

print( Y_cumsum >= 8)


[[ 2  7 13 18]
 [ 4 12 18 23]]
[[False False  True  True]
 [False  True  True  True]]
[[ 6 13 18 27]
 [ 7 12 18 22]]
[[False  True  True  True]
 [False  True  True  True]]


In [28]:
yearly_mean_X = np.mean(S_X, axis=1)
print(yearly_mean_X)

quarterly_mean_Y = np.mean(S_Y, axis=0)
print(quarterly_mean_Y)


[4.5  5.75]
[6.5 6.  5.5 6.5]


In [30]:
numbers = [1, 2, 3, 4, 5]

squared_numbers = map(lambda x: x ** 2, numbers)
print(list(squared_numbers))

[1, 4, 9, 16, 25]


In [31]:
numbers = [1, 2, 3, 4, 5]

even_numbers = filter(lambda x: x % 2 == 0, numbers)
print(list(even_numbers)) 

[2, 4]


In [32]:
from functools import reduce
numbers = [1, 2, 3, 4, 5]

sum_of_numbers = reduce(lambda x, y: x + y, numbers)
print(sum_of_numbers) 


15


In [33]:
square = lambda x: x ** 2
print(square(5)) 

25
