In [17]:
import numpy as np

steps= np.array([[1,6012], [2,7079], [3,6886],[4,7230],[5,4598],[6,5564],[7,6971], [8,7763],[9,8032],[10,9569]]) 
steps_walked = np.array([6012,7079,6886,7230,4598,5564,6971,7763,8032,9569]) 
print(steps)

add_step=np.array([0,2000])
step2=np.add(steps,add_step) 
print('steps after 7am',step2)

x=np.where(step2[:,1]>9000)
print(step2[x]) 

sorted_steps=np.sort(steps_walked)
print(sorted_steps)

sorted=step2[:,1].argsort()
step2[sorted]

[[   1 6012]
 [   2 7079]
 [   3 6886]
 [   4 7230]
 [   5 4598]
 [   6 5564]
 [   7 6971]
 [   8 7763]
 [   9 8032]
 [  10 9569]]
steps after 7am [[    1  8012]
 [    2  9079]
 [    3  8886]
 [    4  9230]
 [    5  6598]
 [    6  7564]
 [    7  8971]
 [    8  9763]
 [    9 10032]
 [   10 11569]]
[[    2  9079]
 [    4  9230]
 [    8  9763]
 [    9 10032]
 [   10 11569]]
[4598 5564 6012 6886 6971 7079 7230 7763 8032 9569]


array([[    5,  6598],
       [    6,  7564],
       [    1,  8012],
       [    3,  8886],
       [    7,  8971],
       [    2,  9079],
       [    4,  9230],
       [    8,  9763],
       [    9, 10032],
       [   10, 11569]])

In [15]:
x=np.where(step2[:,1]>9000)
print(step2[x])


[[    2  9079]
 [    4  9230]
 [    8  9763]
 [    9 10032]
 [   10 11569]]


In [16]:
sorted_steps=steps[steps[:,1].sort()]
print(sorted_steps)

[[[   1 4598]
  [   2 5564]
  [   3 6012]
  [   4 6886]
  [   5 6971]
  [   6 7079]
  [   7 7230]
  [   8 7763]
  [   9 8032]
  [  10 9569]]]


In [21]:
import numpy as np
#sum
arr = np.array([[1, 2], [3, 4]])
print(np.sum(arr)) # Output: 10
print(np.sum(arr, axis=0)) 
print(np.sum(arr, axis=1))


10
[4 6]
[3 7]


In [20]:
#mean
arr = np.array([[1, 2], [3, 4]])
print(np.mean(arr))
print(np.mean(arr, axis=0)) 
print(np.mean(arr, axis=1)) 

2.5
[2. 3.]
[1.5 3.5]


In [22]:
#min
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.max(arr)) 
print(np.max(arr, axis=0)) 
print(np.max(arr, axis=1))
print(np.min(arr)) 
print(np.min(arr, axis=0)) 
print(np.min(arr, axis=1))


4
[3 4]
[2 4]
1
[1 2]
[1 3]


In [23]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.median(arr)) 
print(np.median(arr, axis=0))
print(np.median(arr, axis=1))

2.5
[2. 3.]
[1.5 3.5]


In [25]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.prod(arr)) 
print(np.prod(arr, axis=0)) 
print(np.prod(arr, axis=1)) 

24
[3 8]
[ 2 12]


In [26]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.std(arr))
print(np.std(arr, axis=0)) 
print(np.std(arr, axis=1)) 

1.118033988749895
[1. 1.]
[0.5 0.5]


In [27]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.var(arr))
print(np.var(arr, axis=0)) 
print(np.var(arr, axis=1))  

1.25
[1. 1.]
[0.25 0.25]


In [28]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result) 

[5 7 9]


In [29]:
import numpy as np
arr1 = np.array([4, 5, 6])
arr2 = np.array([1, 2, 3])
result = arr1 - arr2
print(result) 

[3 3 3]


In [30]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 * arr2
print(result)


[ 4 10 18]


In [31]:
import numpy as np
arr1 = np.array([4, 6, 8])
arr2 = np.array([2, 3, 4])
result = arr1 / arr2
print(result) 

[2. 2. 2.]


In [32]:
import numpy as np
arr = np.array([2, 3, 4])
result = arr ** 2
print(result) 

[ 4  9 16]


In [34]:
import numpy as np
arr = np.array([4, 9, 16])
result = np.sqrt(arr)
print(result) 

[2. 3. 4.]


In [35]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 2, 3])
result = arr1 == arr2
print(result)

[False  True  True]


In [36]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
result_mean = np.mean(arr)
result_std = np.std(arr, axis=1)
result_sum = np.sum(arr, axis=0)
print(result_mean) 
print(result_std) 
print(result_sum) 

3.5
[0.81649658 0.81649658]
[5 7 9]
